# Official docker image.
stages :
  - build
  - test
  - deploy

image: docker:latest

services:
  - docker:dind

variables:
    IMAGE_TAG: yossefaz/gis_front:latest

build:
    stage: build
    script:
      - docker build -t $IMAGE_TAG .

test:
  stage: test
  script:
    - docker build -t $IMAGE_TAG .
    - docker run -e CI=true $IMAGE_TAG


deploy:

  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

  only:
    - master

