image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_TAG_PROD: nessgis/gis_front:latest

build_docker_image_group:
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t $IMAGE_TAG_PROD .
    - docker push $IMAGE_TAG_PROD
  only:
    - presentation
