# Official docker image.
image: docker:latest

services:
  - docker:dind

variables:
    IMAGE_TAG: yessefaz/gis_front:latest
test:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker run -e CI=true $IMAGE_TAG

  only:
    - master

prod:
    stage: build
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
      - docker build -t $IMAGE_TAG .
      - docker push $IMAGE_TAG
    only:
      - production
      - master