# Official docker image.
stages :
  - build
  - test
  - deploy

image: docker:latest

services:
  - docker:dind

variables:
    IMAGE_TAG_TEST_GROUP: registry.gitlab.com/gis_manti/gis_front
    IMAGE_TAG_PROD: nessgis/gis_front:latest

build_docker_image_group:
    stage: build
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker build -t $IMAGE_TAG_TEST_GROUP -f Dockerfile.dev .
      - docker push $IMAGE_TAG_TEST_GROUP
    only : 
        - master


