version: "3"

services:
  gis_front:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - "/app/node_modules"
      - "./:/app"
