//actionTypes
export const ADD_LAYER = 'ADD_LAYER'
export const UPDATE_LAYER = 'UPDATE_LAYER'
export const UPDATE_FEATURE_ATTRIBUTES = 'UPDATE_FEATURE_ATTRIBUTES'
export const UPDATE_PUBLISHED_STATUS  = 'UPDATE_PUBLISHED_STATUS'

