//actionTypes
export const ADD_LAYER = 'ADD_LAYER'
export const UPDATE_LAYER = 'UPDATE_LAYER'
export const UPDATE_FEATURE_ATTRIBUTES = 'UPDATE_FEATURE_ATTRIBUTES'
export const SET_UPDATED_IDS = 'SET_UPDATED_IDS'


