enum ActionTypes {
    ADD_OVERLAYS = "ADD_OVERLAYS",
    SET_OVERLAY = "SET_OVERLAY",
    UNSET_OVERLAY= "UNSET_OVERLAY",
    UNSET_OVERLAYS= "UNSET_OVERLAYS",
    SET_OVERLAY_PROPERTY= "SET_OVERLAY_PROPERTY",
}


export default ActionTypes