enum ActionTypes {
    INIT_TOOLS= "INIT_TOOLS",
    RESET_TOOLS= "RESET_TOOLS",
    TOOL_RESETED= "TOOL_RESETED",
    SET_TOOL_FOCUSED= "SET_TOOL_FOCUSED",
    SET_TOOL_PROP= "SET_TOOL_PROP",
    TOGGLE_TOOLS= "OPEN_TOOLS",
    TOGGLE_GROUP_TOOLS= "OPEN_GROUP_TOOLS",
}


export default ActionTypes