enum ActionTypes {
    SET_INTERACTION = "SET_INTERACTION",
    SET_INTERACTIONS = "SET_INTERACTIONS",
    UNSET_INTERACTION = "UNSET_INTERACTION",
    UNSET_INTERACTIONS = "UNSET_INTERACTIONS",
}
export default ActionTypes;