export enum ActionTypes {
  UPDATE_FEATURE_ATTRIBUTES = "UPDATE_FEATURE_ATTRIBUTES",
  SET_SELECTED_FEATURES = "SET_SELECTED_FEATURES",
  SET_CURRENT_FEATURE = "SET_CURRENT_FEATURE",
  SET_CURRENT_FEATURE_LAYER = "SET_CURRENT_FEATURE_LAYER",
  UPDATE_FEATURE = "UPDATE_FEATURE",
  REMOVE_FEATURE = "REMOVE_FEATURE",
  SET_CONTEXT_MENU = "SET_CONTEXT_MENU",
  SET_SPATIAL_LAYER_SELECTION = "SET_SPATIAL_LAYER_SELECTION",
}
