export enum ActionTypes {
    UPDATE_FEATURE_ATTRIBUTES = "UPDATE_FEATURE_ATTRIBUTES",
    SET_SELECTED_FEATURES = "SET_SELECTED_FEATURES",
    SET_CURRENT_FEATURE = "SET_CURRENT_FEATURE",
    UPDATE_FEATURE = "UPDATE_FEATURE",
    REMOVE_FEATURE = "REMOVE_FEATURE",
}


