export enum ActionTypes {
  ADD_LAYER = "ADD_LAYER",
  ADD_LAYER_TO_MAP = "ADD_LAYER_TO_MAP",
  INIT_LAYERS = "INIT_LAYERS",
  SET_LAYER_VISIBLE = "SET_LAYER_VISIBLE",
  SET_LAYER_OPACITY = "SET_LAYER_OPACITY",
  SET_LAYER_SELECTABLE = "SET_LAYER_SELECTABLE",
  LAYER_ADDED = "LAYER_ADDED",
  UPDATE_LAYER = "UPDATE_LAYER",
  SET_SPATIAL_LAYER_SELECTION = "SET_SPATIAL_LAYER_SELECTION",
}
