export enum ActionTypes {
  INIT_TOOLS = "INIT_TOOLS",
  RESET_TOOLS = "RESET_TOOLS",
  TOOL_RESETED = "TOOL_RESETED",
  SET_TOOL_FOCUSED = "SET_TOOL_FOCUSED",
  SET_TOOL_PROP = "SET_TOOL_PROP",
  TOGGLE_STICKY_TOOLS = "TOGGLE_TOOLS",
  CLOSE_DRAG_TOOLS = "CLOSE_DRAG_TOOLS",
  TOGGLE_GROUP_TOOLS = "OPEN_GROUP_TOOLS",
  UNSET_UNFOCUSED_TOOL = "UNSET_UNFOCUSED",
  DRAG_TOOL = "DRAG_TOOL",
}
